# To build and launch (first time):
#   $ docker-compose up -d
# To create new images (--no-cache) to force building from scratch:
#   $ docker-compose build
# To launch again (leave out -d for non daemon launch):
#   $ docker-compose up -d
# Short command for rebuilding and restarting
#   $ docker-compose up -d --build
# To stop containers:
#  $ docker-compose stop
# To clean up containers/images/networks:
#  $ docker system prune
version: '3'
services:
  mongo:
    image: mongo
    networks:
      - mongo_network
      - default
    ports:
      - "27017:27017"
  webgme-hfsm:
    image: webgme-hfsm
    depends_on:
      - mongo
    environment:
      - "NODE_ENV=docker"
    networks:
      - mongo_network
      - default
    ports:
      - "8081:8081"
networks:
  mongo_network:
    driver: bridge
  default:
    driver: bridge
