/*globals define, WebGMEGlobal*/
/*jshint browser: true*/
/**
 * Generated by VisualizerGenerator 1.7.0 from webgme on Thu May 11 2017 10:42:38 GMT-0700 (PDT).
 */

define([
    'js/Constants',
    'js/Utils/GMEConcepts',
    'js/NodePropertyNames'
], function (
    CONSTANTS,
    GMEConcepts,
    nodePropertyNames
) {

    'use strict';

    var HFSMVizControl;

    HFSMVizControl = function (options) {

        this._logger = options.logger.fork('Control');

        this._client = options.client;

        // Initialize core collections and variables
        this._widget = options.widget;

        this.currentNodeInfo = {id: null, children: [], parentId: null};
	
        this._initWidgetEventHandlers();

        this._logger.debug('ctor finished');
    };

    HFSMVizControl.prototype._initWidgetEventHandlers = function () {
        this._widget.onNodeClick = function (id) {
            // Change the current active object
            WebGMEGlobal.State.registerActiveObject(id);
        };
    };

    /* * * * * * * * Visualizer content update callbacks * * * * * * * */
    // One major concept here is with managing the territory. The territory
    // defines the parts of the project that the visualizer is interested in
    // (this allows the browser to then only load those relevant parts).
    HFSMVizControl.prototype.selectedObjectChanged = function (nodeId) {
	var self = this,
	    desc,
	    nodeName;

        if (nodeId && nodeId != this.currentNodeInfo.id) {
            // Remove current territory patterns
            if (self._territoryId) {
		self._client.removeUI(self._territoryId);
            }
	    if (this.currentNodeInfo.id) {
		this._widget._initialize();
	    }

            // Put new node's info into territory rules
            self._selfPatterns = {};

            this.currentNodeInfo.id = nodeId;
            this.currentNodeInfo.parentId = undefined;

            desc = this._getObjectDescriptor(nodeId);
	    if (!desc) {
		self._client.updateTerritory(self._territoryId, self._selfPatterns);
		return;
	    }
            nodeName = (desc && desc.name);
            if (desc) {
                this.currentNodeInfo.parentId = desc.parentId;
            }

            self._selfPatterns[nodeId] = {children: 10};  // Territory "rule"
            self._territoryId = self._client.addUI(self, function (events) {
                self._eventCallback(events);
            });

            // Update the territory
            self._client.updateTerritory(self._territoryId, self._selfPatterns);
        }
    };

    var rootTypes = ['State Machine', 'Library'];
    var excludeTypes = [];

    // This next function retrieves the relevant node information for the widget
    HFSMVizControl.prototype._getObjectDescriptor = function (nodeId) {
        var node = this._client.getNode(nodeId),
            objDescriptor = null;
        if (node) {
	    var metaObj = this._client.getNode(node.getMetaTypeId()),
		metaName = undefined;
	    if (metaObj) {
		metaName = metaObj.getAttribute(nodePropertyNames.Attributes.name);
	    }
	    if (metaName && excludeTypes.indexOf(metaName) == -1) {
		objDescriptor = {
                    id: node.getId(),
		    type: metaName,
                    position: node.getRegistry('position'), // { x, y }
                    childrenIds: node.getChildrenIds(),
                    parentId: node.getParentId(),
                    isConnection: GMEConcepts.isConnection(nodeId)
		};
		node.getAttributeNames().map(function(a) {
		    objDescriptor[a] = node.getAttribute(a);
		});
		objDescriptor.LABEL = objDescriptor.name;
		// add the node pointers if it's a connection
		if (objDescriptor.isConnection) {
		    objDescriptor.src = node.getPointer('src').to;
		    objDescriptor.dst = node.getPointer('dst').to;
		    objDescriptor.LABEL = objDescriptor.Event;
		    if (objDescriptor.Guard) {
			objDescriptor.LABEL += ' [' + objDescriptor.Guard + ']';
		    }
		}
		else if (objDescriptor.type == 'Internal Transition') {
		    objDescriptor.LABEL = objDescriptor.Event;
		    if (objDescriptor.Guard) {
			objDescriptor.LABEL += ' [' + objDescriptor.Guard + ']';
		    }
		}
		// make sure the root level has no parentId
		if (rootTypes.indexOf(objDescriptor.type) > -1)
		    objDescriptor.parentId = null;
	    }
        }

        return objDescriptor;
    };

    /* * * * * * * * Node Event Handling * * * * * * * */
    HFSMVizControl.prototype._eventCallback = function (events) {
        var i = events ? events.length : 0,
            event;

        this._logger.debug('_eventCallback \'' + i + '\' items');

        while (i--) {
            event = events[i];
            switch (event.etype) {

            case CONSTANTS.TERRITORY_EVENT_LOAD:
                this._onLoad(event.eid);
                break;
            case CONSTANTS.TERRITORY_EVENT_UPDATE:
                this._onUpdate(event.eid);
                break;
            case CONSTANTS.TERRITORY_EVENT_UNLOAD:
                this._onUnload(event.eid);
                break;
            default:
                break;
            }
        }

        this._logger.debug('_eventCallback \'' + events.length + '\' items - DONE');
    };

    HFSMVizControl.prototype._onLoad = function (gmeId) {
        var description = this._getObjectDescriptor(gmeId);
	if (description && this._widget)
            this._widget.addNode(description);
    };

    HFSMVizControl.prototype._onUpdate = function (gmeId) {
        var description = this._getObjectDescriptor(gmeId);
	if (description && this._widget)
            this._widget.updateNode(description);
    };

    HFSMVizControl.prototype._onUnload = function (gmeId) {
        if (this._widget)
            this._widget.removeNode(gmeId);
    };

    HFSMVizControl.prototype._stateActiveObjectChanged = function (model, activeObjectId) {
        if (this._currentNodeId === activeObjectId) {
            // The same node selected as before - do not trigger
        } else {
            this.selectedObjectChanged(activeObjectId);
        }
    };

    /* * * * * * * * Visualizer life cycle callbacks * * * * * * * */
    HFSMVizControl.prototype.destroy = function () {
        this._detachClientEventListeners();
        this._client.removeUI(this._territoryId);
    };

    HFSMVizControl.prototype._attachClientEventListeners = function () {
        this._detachClientEventListeners();
        WebGMEGlobal.State.on('change:' + CONSTANTS.STATE_ACTIVE_OBJECT, this._stateActiveObjectChanged, this);
    };

    HFSMVizControl.prototype._detachClientEventListeners = function () {
        WebGMEGlobal.State.off('change:' + CONSTANTS.STATE_ACTIVE_OBJECT, this._stateActiveObjectChanged);
    };

    HFSMVizControl.prototype.onActivate = function () {
        this._attachClientEventListeners();

        if (typeof this._currentNodeId === 'string') {
            WebGMEGlobal.State.registerActiveObject(this._currentNodeId, {suppressVisualizerFromNode: true});
        }
    };

    HFSMVizControl.prototype.onDeactivate = function () {
        this._detachClientEventListeners();
    };

    return HFSMVizControl;
});
