stateDiagram-v2
state "StateA" as S_2f_p_2f_m_2f_A {
  state "StateA1" as S_2f_p_2f_m_2f_A_2f_A1
  state "StateA2" as S_2f_p_2f_m_2f_A_2f_A2
  [*] --> S_2f_p_2f_m_2f_A_2f_A1
}
S_2f_p_2f_m_2f_A : TOGGLE [_root->count < 10] (internal)
state "StateB" as S_2f_p_2f_m_2f_B {
  state "StateB1" as S_2f_p_2f_m_2f_B_2f_B1
  state "StateB2" as S_2f_p_2f_m_2f_B_2f_B2 {
    state "StateB2a" as S_2f_p_2f_m_2f_B_2f_B2_2f_B2a
    state "StateB2b" as S_2f_p_2f_m_2f_B_2f_B2_2f_B2b
    [*] --> S_2f_p_2f_m_2f_B_2f_B2_2f_B2a
  }
  state "H" as S_2f_p_2f_m_2f_B_2f_H
  state "H*" as S_2f_p_2f_m_2f_B_2f_DH
  [*] --> S_2f_p_2f_m_2f_B_2f_B1
}
state S_2f_p_2f_m_2f_c <<choice>>
state S_2f_p_2f_m_2f_d <<choice>>
[*] --> S_2f_p_2f_m_2f_A
S_2f_p_2f_m_2f_A_2f_A1 --> S_2f_p_2f_m_2f_A_2f_A2 : NEXT
S_2f_p_2f_m_2f_B_2f_B2_2f_B2a --> S_2f_p_2f_m_2f_B_2f_B2_2f_B2b : NEXT
S_2f_p_2f_m_2f_B_2f_B1 --> S_2f_p_2f_m_2f_B_2f_B2 : NEXT
S_2f_p_2f_m_2f_c --> S_2f_p_2f_m_2f_B :  [_root->goLeft]
S_2f_p_2f_m_2f_c --> S_2f_p_2f_m_2f_A
S_2f_p_2f_m_2f_c --> S_2f_p_2f_m_2f_d :  [_root->count > 5]
S_2f_p_2f_m_2f_d --> S_2f_p_2f_m_2f_B_2f_B2 :  [_root->count > 8]
S_2f_p_2f_m_2f_d --> S_2f_p_2f_m_2f_A_2f_A1
S_2f_p_2f_m_2f_A --> S_2f_p_2f_m_2f_A_2f_A2 : LOCAL_GO
S_2f_p_2f_m_2f_B --> S_2f_p_2f_m_2f_A : BACK
S_2f_p_2f_m_2f_A --> S_2f_p_2f_m_2f_c : CHOOSE
S_2f_p_2f_m_2f_A --> S_2f_p_2f_m_2f_B_2f_DH : GO_DEEP
S_2f_p_2f_m_2f_B --> [*] : FINISH
S_2f_p_2f_m_2f_A --> S_2f_p_2f_m_2f_B_2f_H : GO_HIST
