stateDiagram-v2
state "Idle" as S_2f_p_2f_m_2f_Idle
S_2f_p_2f_m_2f_Idle : BUTTON_PRESS [pressCount < 1] (internal)
state "Running" as S_2f_p_2f_m_2f_Running
S_2f_p_2f_m_2f_Running : SET_SPEED (internal)
[*] --> S_2f_p_2f_m_2f_Idle
S_2f_p_2f_m_2f_Running --> [*] : FINISH
S_2f_p_2f_m_2f_Idle --> S_2f_p_2f_m_2f_Running : BUTTON_PRESS
S_2f_p_2f_m_2f_Running --> S_2f_p_2f_m_2f_Idle : STOP
